### ISSUE TITLE
PCB gerbers aren't uploading properly to JLCPCB

### ISSUE THREAD

**Issue by evanronnei** [kb-elmo/sesame#1]
I'm not sure if this is an issue with the PCB, or an issue with JLC, but whenever I upload the gerbers for the PCB (using the zip file `/gerbers/sesame_20200810_190522.zip`) the preview image doesn't show up, and the dimensions are not filled in. 

![](https://i.imgur.com/As4pS0V.png)

This issue does not happen with the switchplate and the backplate gerbers. I attempted to generate my own gerbers using [ai03's guide](https://wiki.ai03.com/books/pcb-design/page/pcb-guide-part-6---fill-zones-decoration-and-production#bkmrk-step-14.-production), but I get the same issue.

**Comment by kb-elmo** [comment]
The gerbers in this repo are usually not very up to date and it is better if you just regenerate them fresh by yourself before you try to upload them anywhere.

I did update them now because I made some changes to the files anyways but I can't promise that they will stay up to date in the future.
