### ISSUE TITLE
Registering the Sesami keyboard to Remap

### ISSUE THREAD

**Issue by yoichiro** [kb-elmo/sesame#11]
Could you consider to register Sesame keyboard to Remap?

In the Discord server of Remap, one user asked us about Sesami keyboard.

See: https://discordapp.com/channels/802306358938435605/816488260250370080/1039928619549597796

Sesami keyboard has already been registered to the VIA keyboard repository. However, has not been registered to Remap, therefore, users of Sesami keyboard need to upload the JSON file for VIA to Remap every times to customize the key mappings and etcetra on Remap.

Remap has a completed compatibility of VIA, and you don't need to create other any files for Remap. You can register the Sesami keyboard to Remap by uploading the JSON file you already have and fill in information about the Sesami keyboard. The URL of the application form is: https://remap-keys.app/keyboards

Thanks,
Yoichiro - The owner of Remap.

**Comment by yoichiro** [comment]
@kb-elmo Thank you for submitting the review request! I have just reviewed it and have confirmed the request does not have any problems. The review request of the Sesame keyboard has been approved!

You can fill in information and images of the Sesame keyboard from the following page:
https://remap-keys.app/keyboards
The information and images are shown in the catalog page of the Sesame keyboard:
https://remap-keys.app/catalog/vg11vQsqO5JWre16nmi7

Remap has an ability to flash a firmware from Web browser to MCU directly. You can upload firmwares for Sesame keyboard from the management page:
https://remap-keys.app/keyboards
The firmwares are listed up on the firmware tab of the catalog page. Users can flash them on the page.
https://remap-keys.app/catalog/vg11vQsqO5JWre16nmi7/firmware

If you haveother keyboards, please register them to Remap, too! :)

**Comment by kb-elmo** [comment]
Added a picture and uploaded a firmware file built with up-to-date QMK as well 😃 

I'll consider adding more boards in the future!
