### ISSUE TITLE
Usb device not recognized

### ISSUE THREAD

**Issue by M13G** [kb-elmo/sesame#13]
Hey kb-elmo
I recently redesigned USB C port on Sesame PCB and flashed the ATMEGA32A successfully by using your guide but when I'm trying to connect the PCB to my computer I get this error (USB device not recognized)
I was wondering if you could help me with that
[sesame.zip](https://github.com/user-attachments/files/16946870/sesame.zip)
![IMG_20240910_194034](https://github.com/user-attachments/assets/fe14adfe-4b5e-4f2b-9e13-fe14b99aa6b3)
![IMG_20240910_194111](https://github.com/user-attachments/assets/1bb74f8d-fefd-401e-8dc1-d452705b64ab)
![photo_2024-09-10_18-55-10](https://github.com/user-attachments/assets/58dde95e-3213-49a7-a6b9-bddbf3906a13)

**Comment by kb-elmo** [comment]
Without a schematic of the electronics I can't tell if there is something wrong.

This isn't really the right place to ask for help with your own redesigns or forks of this board though.
If you need help with doing changes to a PCB design on your own the Keyboard Atelier Discord would be the better place to ask for help.

https://discord.gg/b7vwhHS
