### ISSUE TITLE
QMK won't compile via files

### ISSUE THREAD

**Issue by alif1994** [kb-elmo/sesame#2]
With EXTRAKEY_ENABLE set to yes. It will not compile as the error: "There are not enough available interfaces to support all functions."
Solved it by setting it to no in via's rules.mk

**Comment by kb-elmo** [comment]
the VIA keymap is based on recent changes in the QMK master.

You will have to merge the QMK master in your fork and rerun "make git-submodule" to get the newest version of V-USB with the recent changes that enable the fourth HID endpoint in ATMEGA32 based boards which is a requirement for Extrakey to work
