### ISSUE TITLE
gerber to JLC PCB error

### ISSUE THREAD

**Issue by hanhanhan-kim** [kb-elmo/sesame#7]
Hello!
Thanks for designing this very cool keyboard! Looking at this this old issue [here](https://github.com/kb-elmo/sesame/issues/1) , I generated the gerbers myself, and this appears to work for me, except for the switchplate. The generated switchplate gerber fails to result in the correct output, when uploading to JLC PCB. Is there a fix?
Thanks!

**Comment by kb-elmo** [comment]
The gerber viewer at JLCPCB can't process files with that many cutouts.

The files will work. They will just not display correctly in the gerber viewer.

Use 344.5 mm x 121.3 mm as the size for the switchplate PCB.
